suppressMessages(library(ape))
bbg <- c("116f","189f","1buck_m_","2183f","246f","2869f","3237m","369m","4_Female","4lb__f_","584f","7ps__f_","803m","814m","836m","849m","855m","9ks__f_","Bk_6__m_","Hir_13_m_","Hir_5f","Kh_5__m_")
t <- read.tree("/home/gmbluser/mt_remap/trees_v6/world_nomoth.treefile")
h <- sub("^>","",grep("^>",readLines("/home/gmbluser/mt_remap/trees_v2r/world_v2_raw_with_KP677508.fa"),value=TRUE))
desc <- setNames(sub("^[^ ]+ ","",h), sub(" .*","",h))
D <- cophenetic(t); refs <- setdiff(t$tip.label,bbg)
out <- do.call(rbind, lapply(bbg, function(a){ d <- D[a,refs]; r <- names(which.min(d))
  data.frame(animal=a, nearest=r, dist=round(min(d),5), desc=substr(desc[r],1,75)) }))
print(out, row.names=FALSE, right=FALSE)
cat("\nBBG-vs-BBG max patristic distance:", round(max(D[bbg,bbg]),5), "\n")
